[package]
name = "bootloader"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
qemu-test = []
exit-boot-services-test = []
kernel-handoff-test = ["exit-boot-services-test"]

[dependencies]
boot-protocol = { path = "../boot-protocol" }
kernel-image = { path = "../kernel-image" }
uefi = { version = "=0.39.0", default-features = false }

[[bin]]
name = "bootloader"
path = "src/main.rs"
test = false
bench = false
